language: go

install:
  - go get -t ./...
  - go get github.com/dedis/Coding || true

before_install:
  - go get github.com/dedis/kyber
  - cd ${TRAVIS_HOME}/gopath/src/github.com/dedis/kyber
  - git checkout bn256_available
  - go get github.com/dedis/protobuf
  - cd ${TRAVIS_HOME}/gopath/src/github.com/dedis/protobuf
  - git checkout interface_marshaler
  - cd ${TRAVIS_HOME}/gopath/src/github.com/dedis/onet

script:
  - make test

matrix:
  include:
    - name: "64-bit Unit Tests"
    - name: "32-bit Unit Tests"
      env: GOARCH=386

notifications:
  email: false
